### ISSUE TITLE
Can't see "Authentication and Authorization" in adminplus

### ISSUE THREAD

**Issue by maccesch** [jsocol/django-adminplus#38] opened 2016-01-11 14:05 UTC
I followed the install instruction to the dot but I can't the django.contrib.auth stuff in the admin. It also not accessible by url. When I remove adminplus it works again.

I'm using Django 1.9 with Python 3

**Comment by mlorant** [comment] 2016-01-13 09:00
Same behaviour there. Groups & users was correctly discovered with Django 1.8 but aren't available with Django 1.9. It looks like their `admin.register` is done on another `AdminSite`...

**Comment by jsocol** [comment] 2016-01-14 17:53
I haven't had—and probably won't for a little while—a chance to look into this. Anyone find anything?

**Comment by stretch4x4** [comment] 2016-01-30 00:07
Just realised that this might be the same as issue #42 that I raised..
I think these models are being added by an earlier autodiscover.. I have a work around for now but would like to see if a better solution can be found.

**Comment by jsocol** [comment] 2016-02-02 15:09
Yeah, this is a duplicate of #42, closing in favor of that one.

**Closed by jsocol** 2016-02-02 15:09 UTC
